{% set name = "opam" %}
{% set version = "2.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ocaml/opam/releases/download/{{ version }}/opam-full-{{ version }}.tar.gz
  sha256: cb2ab00661566178318939918085aa4b5c35c727df83751fd92d114fdd2fa001

build:
  number: 1
  skip: true  # [win]
  skip: true  # [osx]

requirements:
  build:
    # Note: Conda-forge's default compiler versions are being overridden in recipe/conda_build_config.yaml
    - {{ compiler('cxx') }} # C++ definitely needed: https://github.com/ocaml/opam/issues/4452
    - ocaml >=4.11
    - make >=4.3
    - patch >=2.7.6 # needed by `make ext-lib`
  host:
  run:
    - rsync >=3.2
    - git >=2.30
    - mercurial >=5.6
    - m4 >=1.4.18
    - diffutils >=3.7
    - unzip >=6
    - patch >=2.7.6
    - bubblewrap  # [linux]

test:
  commands:
    - opam

about:
  home: https://github.com/ocaml/opam
  summary: A package manager for OCaml
  description: |
    opam is a source-based package manager. It supports multiple simultaneous compiler
    installations, flexible package constraints, and a Git-friendly development workflow.
  license: LGPL-2.1-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fasiha
